spring:
  application:
    name: SpringEmployeeServer
  datasource:
    url: jdbc:mysql://localhost:3306/employee_directory
    username: springstudent
    password: Spr1ng$tudent
  data:
    rest:
      base-path: /magic-api
      default-page-size: 3